############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Tulisan"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Tulisan"
  name = "Nasional"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Tulisan"
  name = "Internasional"
  url = "categories/"
  weight = 2

[[main]]
name = "Tentang Kami"
url = "about/"
weight = 3

[[main]]
name = "Kontak Kami"
url = "contact/"
weight = 4



# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Tentang Kami"
url = "about/"
weight = 2

[[footer]]
name = "Kontak"
url = "contact/"
weight = 3

[[footer]]
name = "Kebijakan Konten"
url = "privacy-policy/"
weight = 4
